apiVersion: v1
kind: Secret
metadata:
  name: argocd-secret
  namespace: argocd
stringData:
  accounts.agutierrez.password: $2b$12$B67q/jwVJg/ecXyA8XoHt.2xbWNyVIYlBgCryu3FPKrwBe1JoOiCi
  accounts.bmartinez.password: $2b$12$L776rbOQOy2Xnpfx9VuCU.dQu412Bsd4xuqqOe6pyjJFUm9cBXSF.
  accounts.dburgos.password: $2b$12$ygxnO8q62.nZYLlvZz0.Z.rlKYvAz3daHFruSm3aoNsEX5lxG8Dvi
  accounts.imarin.password: $2b$12$1lzuk9IxcyW/HgJB.SApOee6Fs0BKZ44TUzB4JFzg7v2PNBFhbNTy
  accounts.jgodoy.password: $2b$12$s/WC90FQ/MSbZJIKLCHn0eJQ//lqcTrixJmKq/hKOHQ4g7s.BBWa.
  accounts.jguerra.password: $2b$12$f8DhlZYGSqGVmQBJ2uSJFuBzWWMZ/ElCNxUvmwpm.M0n6zbHnRjs2
  accounts.jmontealegre.password: $2b$12$q.BPCP4xpXzEv0Hs4iiSHuTKGRbWvNsl9GLO9VVv/pG7DDcfyc1JO
  accounts.lruiz.password: $2b$12$7Lx0SjpMB3L2zaCM5kwTyOVcPnH7LvBl8s00F5ExmXAjoLgY2jR6K
  accounts.nmayorquin.password: $2b$12$I1rsMw5ex1HCI0rgl4HkCe7EZ1Sue7SiaKvnuFEN6y2CRHTiBdqNi
  accounts.ycastiblanco.password: $2b$12$snAIc6U3FPTq9yBFNkl9ge./6U9887zomh7rt9KIqe7jmx2VvbOnm
  accounts.pbeltran.password: $2b$12$hGW16cuiNqJgZnA64cCahe1/o7QJc0A8CZaZ5vBGzg7H7.B4uOewu
  # Additional secrets can go here
