apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-configuration
  namespace: ingress-nginx
data:
  http-snippet: |
    location /.well-known/acme-challenge/ {
      root /etc/nginx/acme-challenge;
      try_files $uri =404;
    }

